# Generated by Django 4.1.7 on 2023-04-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceUploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(blank=True, max_length=255, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "blog",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Resourceuploader_from_blog",
                        to="blog.blog",
                    ),
                ),
            ],
        ),
    ]
